- type: rss
  limit: 10
  collapse-after: 5
  cache: 12h
  feeds:
    - url: https://xkcd.com/rss.xml
      title: XKCD
    - url: https://universe.eveonline.com/feed/new-eden-news.rss
      title: EVE Universe
    - url: http://www.gameinformer.com/feeds/thefeedrss.aspx
      title: Game Informer
    - url: http://blogs.msdn.com/webdevtools/rss.xml
      title: ASP.NET Web Tools Blog
    - url: https://devblogs.microsoft.com/feed/landingpage
      title: Microsoft Dev Blogs
    - url: https://ciechanow.ski/atom.xml
    - url: https://www.joshwcomeau.com/rss.xml
      title: Josh Comeau
    - url: https://samwho.dev/rss.xml
    - url: https://ishadeed.com/feed.xml
      title: Ahmad Shadeed
