- type: weather
  location: London, United Kingdom
  units: metric # alternatively "imperial"
  hour-format: 12h # alternatively "24h"
  # Optionally hide the location from being displayed in the widget
  # hide-location: true
