- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - $include: widgets/calendar.yml
        - $include: widgets/weather-london.yml
        - $include: widgets/weather-forecast.yml
        - $include: widgets/rss-home.yml

    - size: full
      widgets:
        - $include: widgets/search-google.yml
        - $include: widgets/group-home-news.yml
        - $include: widgets/videos-home-youtube.yml

    - size: small
      widgets:
        - $include: widgets/server-stats.yml
        - $include: widgets/docker-containers.yml
        - $include: widgets/monitor-home-sites.yml
        - $include: widgets/markets-home-summary.yml
