- name: Markets
  columns:
    - size: small
      widgets:
        - $include: widgets/markets-indices.yml
        - $include: widgets/markets-crypto.yml
        - $include: widgets/markets-stocks.yml

    - size: full
      widgets:
        - $include: widgets/rss-markets-news.yml
        - $include: widgets/group-markets-reddit.yml

        # - type: videos
        #   style: grid-cards
        #   collapse-after-rows: 3
        #   channels:
        #     - UCvSXMi2LebwJEM1s4bz5IBA # New Money
        #     - UCV6KDgJskWaEckne5aPA0aQ # Graham Stephan
        #     - UCAzhpt9DmG6PnHXjmJTvRGQ # Federal Reserve

    - size: small
      widgets:
        - $include: widgets/rss-markets-papers.yml
